### ISSUE TITLE
Difficoltà nell'unire due oggetti

### ISSUE THREAD

**Issue by Giacomuzzo** [strumet/labmod17_ex2#2]
![listelli diagonali_](https://user-images.githubusercontent.com/32162157/32991411-5d086f20-cd3b-11e7-9b6d-da2fa7989747.JPG)
![listelli diagonali_1](https://user-images.githubusercontent.com/32162157/32991412-5d218e10-cd3b-11e7-99e7-94439d3baa88.JPG)

Sto riscontrando delle difficoltà nel realizzare i listelli diagonali perchè dovrebbero connettere dei border della parte superiore e dei border sulla parte inferiore, che però fanno parte di due elementi separati.
Vorrei applicare il comando bridge ai due border però non riesco a selezionarli, ho provato anche a selezionare entrambi gli oggetti e a fonderli in una editable poly ma non funziona.
Allego gli screen della schermata.

**Comment by strumet** [comment]
Ciao Chiara,
per effettuare un bridge è necessario che i due border si trovino sullo stesso oggetto (devi quindi fonderli insieme col comando "attach") e che il numero di edges sia uguale in entrambi i border.
Ti consiglio di procedere prima effettuando il bridge tra 2 soli edge (uno per ogni border) e poi di collegare i restanti edges.
Se non funzionasse fammi sapere dove posso scaricare il tuo file e vedrò di dargli un'occhiata.

**Comment by Giacomuzzo** [comment]
Sono riuscita ad unirli e a creare i listelli diagonali, La ringrazio!
